#database setup for different environment

development:
  adapter: postgresql
  database: community_development
  encoding: unicode
  pool: 5
  username: satya
  password: 

development:
  adapter: postgresql
  database: community_test
  encoding: unicode
  pool: 5
  username: satya
  password: 

production:
  adapter: postgresql
  database: community_development
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
